import Head from 'next/head';
import styled from 'styled-components';

const Container = styled.div``;

export default function Home() {
  return (
    <Container>
      <Head>
        <title>초원</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Container>
  );
}
